### PR TITLE
The Big Cleanup

### PR DESCRIPTION
**Pull request by jqr**
This is a lot of changes around general improvement and bringing this agent up to our standards.

* add standard `script/*` commands
* support `count` argument on `increment` or `gauge` calls
* use preferred ordering of `notice` call
* general whitespace and comment cleanup
* use `LinkedBlockingQueue` instead of `LinkedBlockingDeque` so polling isn't required
* use daemon threads so the connection thread will not block application exit
* use our standard exponential back off delays
* fix error count clearing
* only send metrics once authentication succeeds
* allow common options to be set on a connection (host, port, enabled, synchronous, api key).

More work remains but this is in a good position to integrate.

### CODE REVIEW

**Comment by jqr** [comment]
Eek, sorry PR to wrong repo :)

**Comment by bvarner** [comment]
Hey, no worries! I'd be interested in knowing if there will be or is an 'official' release, though. :-)

P.S. An upstream PR would be welcomed...

**Comment by jqr** [comment]
There will be. You guys provided a great start, so thank you :)

We're working adding more failure/error handling and standardizing arguments, etc. and then should have a release within a week or two.

**Comment by jqr** [comment]
For the sake of record keeping, this PR became https://github.com/Instrumental/instrumental-agent-java/pull/1.

**Pull request closed without merging**
